spring:
  datasource:
    url: jdbc:h2:mem:brainitdesafio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 900000 # 15 minutos
